dataset_info:
  batch_size: 1
  dataset_name: sketchfab-small
  dataset_rng_seed: 0
  dataset_root_dir: datasets/sketchfab-small
  fov: 60.0
  height_px: 300
  k: 40
  local_max_angle: 3.0
  max_angle: 180
  max_k_ratio: 5.0
  max_num_mesh: 2
  max_r: 3.0
  max_subsample: 10
  max_translate_ratio: 2.0
  mesh_filename:
  - train/a_sculpture_in_air_force_museum_of_vietnam/SimpleBake_Bakes/mesh.glb
  - train/amphitrite_-_louvre_museum_low_definition/SimpleBake_Bakes/mesh.glb
  - train/angel/SimpleBake_Bakes/mesh.glb
  - train/angel_playing_harp/SimpleBake_Bakes/mesh.glb
  - train/angel_sculpture_3d_scan_einscan-s/SimpleBake_Bakes/mesh.glb
  - train/angel_statue_in_fossano/SimpleBake_Bakes/mesh.glb
  - train/angels/SimpleBake_Bakes/mesh.glb
  - train/archelon_-_dragon_sea_turtle/SimpleBake_Bakes/mesh.glb
  - train/baptismal_angel_kneeling/SimpleBake_Bakes/mesh.glb
  - train/buddha/SimpleBake_Bakes/mesh.glb
  - train/bust_of_a_roman/SimpleBake_Bakes/mesh.glb
  - train/chateau_de_chamarande_-_france/SimpleBake_Bakes/mesh.glb
  - train/chinese_dragon/SimpleBake_Bakes/mesh.glb
  - train/cobra_statue/SimpleBake_Bakes/mesh.glb
  - train/compressor_scan/SimpleBake_Bakes/mesh.glb
  - train/dragon-stl/SimpleBake_Bakes/mesh.glb
  - train/dragon_chalice/SimpleBake_Bakes/mesh.glb
  - train/dragon_decimated_sculpt/SimpleBake_Bakes/mesh.glb
  - train/empire_vase/SimpleBake_Bakes/mesh.glb
  - train/equestrian_statue_of_napoleon/SimpleBake_Bakes/mesh.glb
  - train/ganesha/SimpleBake_Bakes/mesh.glb
  - train/gargo/SimpleBake_Bakes/mesh.glb
  - train/girl_with_dog/SimpleBake_Bakes/mesh.glb
  - train/golden_ephant/SimpleBake_Bakes/mesh.glb
  - train/grey_fox_skull/SimpleBake_Bakes/mesh.glb
  - train/guanyin/SimpleBake_Bakes/mesh.glb
  - train/happy_buddha_stanford/SimpleBake_Bakes/mesh.glb
  - train/king_of_narnia_aslan/SimpleBake_Bakes/mesh.glb
  - train/little_angle/SimpleBake_Bakes/mesh.glb
  - train/madona_sculpture/SimpleBake_Bakes/mesh.glb
  - train/man_on_bench_statue_photogrammetry/SimpleBake_Bakes/mesh.glb
  - train/maria_fjodorovna_barjatinskaja/SimpleBake_Bakes/mesh.glb
  - train/neptune_-_louvre_museum/SimpleBake_Bakes/mesh.glb
  - train/ox_statue_kek_lok_si_buddhist_temple_penang/SimpleBake_Bakes/mesh.glb
  - train/panasonic_gh4_body/SimpleBake_Bakes/mesh.glb
  - train/pieta/SimpleBake_Bakes/mesh.glb
  - train/roman_sphinx/SimpleBake_Bakes/mesh.glb
  - train/stanford_armadillo_pbr/SimpleBake_Bakes/mesh.glb
  - train/the_death_and_the_mother/SimpleBake_Bakes/mesh.glb
  - train/the_elephant_god_ganesha/SimpleBake_Bakes/mesh.glb
  - train/the_god_vishnu/SimpleBake_Bakes/mesh.glb
  - train/the_infant_mozart/SimpleBake_Bakes/mesh.glb
  - train/tower_well_valve/SimpleBake_Bakes/mesh.glb
  - train/two_wrestlers_in_combat_repost/SimpleBake_Bakes/mesh.glb
  - train/warcraft_alliance_statue/SimpleBake_Bakes/mesh.glb
  - train/wooden_buddha_statuette/SimpleBake_Bakes/mesh.glb
  - train/wooden_dragon/SimpleBake_Bakes/mesh.glb
  - train/xyz_rgb_dragon/SimpleBake_Bakes/mesh.glb
  mesh_scale: 1.0
  min_k_ratio: 0.3
  min_num_mesh: 1
  min_r: 0.5
  min_subsample: 1
  mix_meshes: false
  n_imgs: 30
  n_target_imgs: 1
  num_threads: 10
  pcd_subsample: 2
  radius_scale: 2.0
  rand_r: 0.5
  ray_perturbation_angle: 3
  render_method: ray_cast
  target_height_px: 50
  target_width_px: 50
  test_mesh_filename:
  - test/baron_seutin/SimpleBake_Bakes/mesh.glb
  - test/bust_of_a_rhetorician_restored/SimpleBake_Bakes/mesh.glb
  - test/cupid/SimpleBake_Bakes/mesh.glb
  - test/drunkard_-_cap_re/SimpleBake_Bakes/mesh.glb
  - test/lambert_de_maestricht_and_liege/SimpleBake_Bakes/mesh.glb
  - test/marie-madeleine/SimpleBake_Bakes/mesh.glb
  - test/relief_in_terracotta/SimpleBake_Bakes/mesh.glb
  - test/seated_jew/SimpleBake_Bakes/mesh.glb
  - test/seated_lady/SimpleBake_Bakes/mesh.glb
  - test/statue_of_zenobe_gramme/SimpleBake_Bakes/mesh.glb
  - test/the_charity/SimpleBake_Bakes/mesh.glb
  - test/vulcan/SimpleBake_Bakes/mesh.glb
  - test/young_roman_as_asklepios/SimpleBake_Bakes/mesh.glb
  texture_crop_method: 20-200
  texture_filenames: null
  texture_mode: imagenet
  total: 10000
  total_combined: null
  use_bucket_sampler: true
  width_px: 300
model_info:
  dim_feature: 64
  dim_input_layers:
  - 32
  - 64
  dim_mlp: 64
  direction_param: norm_vec
  dropout: 0.1
  estimate_image_rendering_weights: true
  estimate_surface_normal_weights: false
  learn_dist: false
  nonlinearity: silu
  num_heads: 4
  num_layers: 4
  positional_encoding_include_input: true
  positional_encoding_log_sampling: true
  positional_encoding_num_functions: 0
  use_dist_as_input: false
  use_dps_as_input: false
  use_dpsuv_as_input: true
  use_feature_indicator: true
  use_pr: true
  use_rgb_as_input: true
  use_rgb_indicator: true
  use_vdir_as_input: true
  use_zdir_as_input: true
optim_info:
  focal_loss_alpha: 0.5
  focal_loss_gamma: 2.0
  learn_ray_rgb: true
  learning_rate: 0.0001
  loss_rgb_type: l1
  loss_weight_hit: 1.0
  loss_weight_normal: 1.0
  loss_weight_normal_l1: 0.0
  loss_weight_plane_normal: 0
  loss_weight_plane_normal_l1: 0.0
  loss_weight_rgb: 1.0
  loss_weight_rgb_normal: 0.0
  loss_weight_rgb_normal_dot: 0.0
  loss_weight_rgb_normal_dot_l1: 0
  loss_weight_t: 10.0
  loss_weight_t_l1: 0.0
  lr_factor: 0.1
  max_grad_val: 1.0
  num_warmup_steps: 4000
  optim_method: adam_tf
  pcd_noise_std: 0.0
  random_drop_rgb_rate: 0.5
  random_drop_sample_feature_rate: 0.5
  use_amp: false
process_info:
  ddp_type: ddp
  exclude_dirs:
  - artifacts
  - datasets
  - checkpoints
  exp_tag: exp_l1
  exp_tag_first: false
  find_unused_parameters: false
  log_every_num_test_batch: 1
  log_every_num_train_batch: 1
  log_every_num_valid_batch: 1
  max_test_epoch_batches: 100
  max_train_epoch_batches: 500
  max_valid_epoch_batches: 100
  output_dir: artifacts
  save_every_num_epoch: 1
  test_every_num_epoch: 1
  use_torchrun: true
  validate_every_num_epoch: 1
  visualize_every_num_test_batch: 10
  visualize_every_num_train_batch: 300
  visualize_every_num_valid_batch: 30
